#!/usr/bin/env node
/**
 * generate_catalog.js
 * Builds PRESET_CATALOG.md - the routing catalog Claude Code reads on-demand to match a
 * task description to the best preset (see docs/ROUTING_SYSTEM.md for the architecture).
 *
 * Unlike generate_skills.js / generate_commands.js this is a SINGLE aggregated file, not
 * one file per item, so there is no per-entry hand-tuning to protect - every run fully
 * regenerates it from the latest HTML. Always safe to re-run.
 *
 * Source of truth: v41 HTML (PM object - name, agent count, description, use-case,
 * pros/cons, token range, cost range, flow pattern - all already computed by the app
 * itself, not re-derived here).
 * Target: ~/.claude/PRESET_CATALOG.md (GLOBAL, on-demand load per docs/ROUTING_SYSTEM.md)
 *
 * Usage: node generate_catalog.js
 */

const fs = require('fs');
const path = require('path');
const os = require('os');

const HTML_PATH = path.join(__dirname, 'v41', 'AGENT_TEAMS_CONFIGURATOR_v41.html');
// --out <path> overrides the default (mainly for testing without touching the real
// global catalog) - normal use is just `node generate_catalog.js`, no flags.
const outFlagIdx = process.argv.indexOf('--out');
const CATALOG_PATH = outFlagIdx !== -1 && process.argv[outFlagIdx + 1]
  ? path.resolve(process.argv[outFlagIdx + 1])
  : path.join(os.homedir(), '.claude', 'PRESET_CATALOG.md');

// Same brace-matching extractor used by generate_commands.js - kept local rather than
// shared, matching how this repo's two other generator scripts are each self-contained.
function extractJSObject(html, varName) {
  const markers = [`const ${varName}={`, `const ${varName} = {`, `const ${varName}= {`, `const ${varName} ={`];
  let startIdx = -1;
  for (const m of markers) { startIdx = html.indexOf(m); if (startIdx !== -1) break; }
  if (startIdx === -1) throw new Error(`Could not find ${varName} in HTML`);
  const braceStart = html.indexOf('{', startIdx);
  let depth = 0, inString = false, stringChar = '';
  for (let i = braceStart; i < html.length; i++) {
    const ch = html[i], next = i + 1 < html.length ? html[i + 1] : '';
    if (!inString && ch === '/' && next === '/') { while (i < html.length && html[i] !== '\n') i++; continue; }
    if (inString) { if (ch === '\\') { i++; continue; } if (ch === stringChar) inString = false; continue; }
    if (ch === "'" || ch === '"' || ch === '`') { inString = true; stringChar = ch; continue; }
    if (ch === '{') depth++;
    if (ch === '}') {
      depth--;
      if (depth === 0) {
        try { return new Function('return ' + html.substring(braceStart, i + 1))(); }
        catch (e) { throw new Error(`Failed to eval ${varName}: ${e.message}`); }
      }
    }
  }
  throw new Error(`Could not find matching brace for ${varName}`);
}

const TIERS = [
  { label: 'Minimal', lo: 2, hi: 3 },
  { label: 'Core', lo: 4, hi: 6 },
  { label: 'Advanced', lo: 7, hi: 11 },
  { label: 'Enterprise / flagship', lo: 12, hi: 99 },
];

function build() {
  const html = fs.readFileSync(HTML_PATH, 'utf-8');
  const PM = extractJSObject(html, 'PM');
  const ids = Object.keys(PM);

  let out = '';
  out += '# Preset Catalog\n\n';
  out += `Auto-generated by \`generate_catalog.js\` from \`v41/AGENT_TEAMS_CONFIGURATOR_v41.html\`. `;
  out += `Do not hand-edit - re-run the script instead. ${ids.length} presets, grouped by team size.\n\n`;
  out += 'How to use this file: match the task description against the "Use when" column below, ';
  out += 'confirm the fit against pros/cons, then run the matching command (`/<id>`). ';
  out += 'See `docs/ROUTING_SYSTEM.md` for the full routing architecture and token budget.\n\n';

  // --- Decision guide: one table per tier, sorted by agent count ---
  out += '## Decision guide\n\n';
  TIERS.forEach(tier => {
    const inTier = ids
      .filter(id => PM[id].c >= tier.lo && PM[id].c <= tier.hi)
      .sort((a, b) => PM[a].c - PM[b].c);
    if (!inTier.length) return;
    out += `### ${tier.label} (${tier.lo}-${tier.hi === 99 ? '27' : tier.hi} agents, ${inTier.length} presets)\n\n`;
    out += '| Command | Name | Agents | Use when |\n';
    out += '|---------|------|--------|----------|\n';
    inTier.forEach(id => {
      const p = PM[id];
      const use = (p.use || '').replace(/\|/g, '\\|');
      out += `| \`/${id.replace(/_/g, '-')}\` | ${p.i || ''} ${p.n} | ${p.c} | ${use} |\n`;
    });
    out += '\n';
  });

  // --- Full per-preset detail: description, pros/cons, cost, flow pattern ---
  out += '## Preset details\n\n';
  TIERS.forEach(tier => {
    const inTier = ids
      .filter(id => PM[id].c >= tier.lo && PM[id].c <= tier.hi)
      .sort((a, b) => PM[a].c - PM[b].c);
    if (!inTier.length) return;
    out += `### ${tier.label}\n\n`;
    inTier.forEach(id => {
      const p = PM[id];
      out += `#### \`/${id.replace(/_/g, '-')}\` - ${p.i || ''} ${p.n} (${p.c} agents)\n\n`;
      if (p.dsc) out += `${p.dsc}\n\n`;
      if (p.use) out += `**Use when:** ${p.use}\n\n`;
      if (Array.isArray(p.p) && p.p.length) out += `**Strengths:**\n${p.p.map(x => `- ${x}`).join('\n')}\n\n`;
      if (Array.isArray(p.m) && p.m.length) out += `**Limits / DO NOT use when:**\n${p.m.map(x => `- ${x}`).join('\n')}\n\n`;
      const meta = [];
      if (p.t) meta.push(`~${p.t.replace(/^~/, '')} tokens`);
      if (p.$) meta.push(`${p.$} est. cost`);
      if (p.pt) meta.push(`flow: ${p.pt}`);
      if (meta.length) out += `*${meta.join(' | ')}*\n\n`;
    });
  });

  // --- Fallback ---
  out += '## Fallback\n\n';
  out += 'None of the 62 presets fit? Assemble a custom pipeline from the 60-agent catalog directly - ';
  out += 'see `docs/SKILLS_ARCHITECTURE.md` for the full agent list, or open the app and drag agents onto ';
  out += 'the canvas by hand to design a one-off team and export its prompt.\n';

  return out;
}

function main() {
  const md = build();
  const dir = path.dirname(CATALOG_PATH);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(CATALOG_PATH, md, 'utf-8');
  const presetCount = (md.match(/^#### `\//gm) || []).length;
  console.log(`Wrote ${CATALOG_PATH}`);
  console.log(`${presetCount} presets catalogued, ${md.length} chars (~${Math.round(md.length / 4)} tokens).`);
}

main();
